sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.4.1

before_install:
 - curl -sSL https://get.docker.com/ | sudo sh
 - sudo pip install docker-compose
 - grep -vi proxy docker-compose.yml > docker-compose.yml
 - grep -vi environment docker-compose.yml > docker-compose.yml
 - grep -vi proxy docker-compose.yml > Dockerfile
 - grep -vi proxy docker-compose.yml > Dockerfile_shinyr
 - docker build -t="cfphxd/shiny" -f Dockerfile_shinyr .

script:
  - docker-compose up -d
  - docker-compose ps

notifications:
  irc:
    channels:
      - "irc.freenode.org#inasafe"
    use_notice: true

  email:
    - helge.dzierzon@plantandfood.co.nz
