sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.4.1

before_install:
 - sudo pip install docker-compose
 - docker build -t="cfphxd/shiny" -f Dockerfile_shinyr .

script:
  - docker-compose up -d
  - docker-compose ps

