db:
  image: postgres
  volumes:
    - .:/dat
  ports:
    - "5434:5432"
  environment:
     - dummy:dummy
     - http_proxy:http://proxy.pfr.co.nz:8080
     - https_proxy:http://proxy.pfr.co.nz:8080
     - no_proxy:localhost,127.0.0.1,*.pfr.co.nz,::1
web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
    - /input:/input
    - /output:/output
    - /workspace:/workspace
  ports:
    - "8000:8000"
  links:
    - db
  environment:
     - dummy:dummy
     - http_proxy:http://proxy.pfr.co.nz:8080
     - https_proxy:http://proxy.pfr.co.nz:8080
     - no_proxy:localhost,127.0.0.1,*.pfr.co.nz,::1
shinyr:
  build: .
  dockerfile: Dockerfile_shinyr
  volumes:
    - /home/cfphxd/ShinyApps/pinf/seafood:/srv/shiny-server/12_seafood/
    - /srv/shinylog/:/var/log/
  links:
    - web
  ports:
    - "3839:3838"
  environment:
     - dummy:dummy
     - http_proxy:http://proxy.pfr.co.nz:8080
     - https_proxy:http://proxy.pfr.co.nz:8080
     - no_proxy:localhost,127.0.0.1,*.pfr.co.nz,::1
pyrat:
  image: cfljam/pyrat
  volumes:
    - /input:/input
    - /output:/output
    - /workspace:/workspace
  ports:
    - "8889:8888"
  links:
    - web
  environment:
     - dummy:dummy
     - http_proxy:http://proxy.pfr.co.nz:8080
     - https_proxy:http://proxy.pfr.co.nz:8080
     - no_proxy:localhost,127.0.0.1,*.pfr.co.nz,::1
mongo:
  image: mongo
cassandra:
  image: cassandra
  environment:
     - dummy:dummy
     - http_proxy:http://proxy.pfr.co.nz:8080
     - https_proxy:http://proxy.pfr.co.nz:8080
     - no_proxy:localhost,127.0.0.1,*.pfr.co.nz,::1
rstudio:
  #image: rocker/rstudio
  build: .
  dockerfile: Dockerfile_rstudio
  volumes:
    - /input:/input
    - /output:/output
    - /workspace:/workspace
  links:
    - web
  ports:
     - "8788:8787"
  environment:
     - dummy:dummy
     - http_proxy:http://proxy.pfr.co.nz:8080
     - https_proxy:http://proxy.pfr.co.nz:8080
     - no_proxy:localhost,127.0.0.1,*.pfr.co.nz,::1
anaconda:
  image: continuumio/anaconda
  volumes:
    - /input:/input
    - /output:/output
    - /workspace:/workspace 
  links:
    - web
  ports:
    - "8890:8888"
  environment:
     - http_proxy:http://proxy.pfr.co.nz:8080
     - https_proxy:http://proxy.pfr.co.nz:8080
     - no_proxy:localhost,127.0.0.1,*.pfr.co.nz,::1

