db:
  image: postgres
  volumes:
    - .:/dat
  ports:
    - "5434:5432"
web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
shinyr:
  image: cfphxd/shiny
  volumes:
    - /home/cfphxd/ShinyApps/pinf/seafood:/srv/shiny-server/12_seafood/
    - /srv/shinylog/:/var/log/
  ports:
    - "3839:3838"
pyrat:
  image: cfljam/pyrat
  ports:
    - "8889:8888"
mongo:
  image: mongo
cassandra:
  image: cassandra
